#!/bin/bash

# Load utils
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
if [ -f "$DOTFILES_DIR/lib/utils.sh" ]; then
    source "$DOTFILES_DIR/lib/utils.sh"
else
    echo "Error: utils.sh not found at $DOTFILES_DIR/lib/utils.sh"
    exit 1
fi

# Load defaults utilities
if [ -f "$DOTFILES_DIR/lib/defaults.sh" ]; then
    source "$DOTFILES_DIR/lib/defaults.sh"
else
    echo "Error: defaults.sh not found at $DOTFILES_DIR/lib/defaults.sh"
    exit 1
fi

check_macos

echo "Syncing Finder settings..."

# Create settings file with specific Finder preferences only
cat > "$SCRIPT_DIR/finder-settings.txt" << 'EOF'
# Finder Settings Configuration
# Generated by backup.sh

# Show/Hide Files and Extensions
AppleShowAllExtensions
ShowPathbar
ShowStatusBar

# Desktop Items
ShowHardDrivesOnDesktop
ShowExternalHardDrivesOnDesktop
ShowMountedServersOnDesktop
ShowRemovableMediaOnDesktop

# View Settings
FXPreferredViewStyle
_FXSortFoldersFirst
_FXShowPosixPathInTitle
FXDefaultSearchScope
NewWindowTarget

# Other
QuitMenuItem
WarnOnEmptyTrash
FXEnableExtensionChangeWarning
EOF

echo "" >> "$SCRIPT_DIR/finder-settings.txt"
echo "# Current Settings:" >> "$SCRIPT_DIR/finder-settings.txt"

# Save only essential Finder settings using shared function
save_defaults_setting "NSGlobalDomain" "AppleShowAllExtensions" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "AppleShowAllFiles" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "ShowPathbar" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "ShowStatusBar" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "ShowHardDrivesOnDesktop" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "ShowExternalHardDrivesOnDesktop" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "ShowMountedServersOnDesktop" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "ShowRemovableMediaOnDesktop" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "FXPreferredViewStyle" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "_FXSortFoldersFirst" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "_FXShowPosixPathInTitle" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "FXDefaultSearchScope" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "NewWindowTarget" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "QuitMenuItem" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "WarnOnEmptyTrash" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.finder" "FXEnableExtensionChangeWarning" "$SCRIPT_DIR/finder-settings.txt"

# Desktop services settings
save_defaults_setting "com.apple.desktopservices" "DSDontWriteNetworkStores" "$SCRIPT_DIR/finder-settings.txt"
save_defaults_setting "com.apple.desktopservices" "DSDontWriteUSBStores" "$SCRIPT_DIR/finder-settings.txt"

echo "✓ Essential Finder settings synced to finder-settings.txt"