#!/bin/bash

# Load utils
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
if [ -f "$DOTFILES_DIR/lib/utils.sh" ]; then
    source "$DOTFILES_DIR/lib/utils.sh"
else
    echo "Error: utils.sh not found at $DOTFILES_DIR/lib/utils.sh"
    exit 1
fi

check_macos

echo "Syncing Finder settings..."

# Create settings file with specific Finder preferences only
cat > "$SCRIPT_DIR/finder-settings.txt" << 'EOF'
# Finder Settings Configuration
# Generated by sync.sh

# Show/Hide Files and Extensions
AppleShowAllExtensions
ShowPathbar
ShowStatusBar

# Desktop Items
ShowHardDrivesOnDesktop
ShowExternalHardDrivesOnDesktop
ShowMountedServersOnDesktop
ShowRemovableMediaOnDesktop

# View Settings
FXPreferredViewStyle
_FXSortFoldersFirst
_FXShowPosixPathInTitle
FXDefaultSearchScope
NewWindowTarget

# Other
QuitMenuItem
WarnOnEmptyTrash
FXEnableExtensionChangeWarning
EOF

# Function to save specific settings
save_specific_setting() {
    local domain="$1"
    local key="$2"
    
    value=$(defaults read "$domain" "$key" 2>/dev/null)
    if [ -n "$value" ]; then
        echo "$domain|$key=$value" >> "$SCRIPT_DIR/finder-settings.txt"
    fi
}

echo "" >> "$SCRIPT_DIR/finder-settings.txt"
echo "# Current Settings:" >> "$SCRIPT_DIR/finder-settings.txt"

# Save only essential Finder settings
save_specific_setting "NSGlobalDomain" "AppleShowAllExtensions"
save_specific_setting "com.apple.finder" "AppleShowAllFiles"
save_specific_setting "com.apple.finder" "ShowPathbar"
save_specific_setting "com.apple.finder" "ShowStatusBar"
save_specific_setting "com.apple.finder" "ShowHardDrivesOnDesktop"
save_specific_setting "com.apple.finder" "ShowExternalHardDrivesOnDesktop"
save_specific_setting "com.apple.finder" "ShowMountedServersOnDesktop"
save_specific_setting "com.apple.finder" "ShowRemovableMediaOnDesktop"
save_specific_setting "com.apple.finder" "FXPreferredViewStyle"
save_specific_setting "com.apple.finder" "_FXSortFoldersFirst"
save_specific_setting "com.apple.finder" "_FXShowPosixPathInTitle"
save_specific_setting "com.apple.finder" "FXDefaultSearchScope"
save_specific_setting "com.apple.finder" "NewWindowTarget"
save_specific_setting "com.apple.finder" "QuitMenuItem"
save_specific_setting "com.apple.finder" "WarnOnEmptyTrash"
save_specific_setting "com.apple.finder" "FXEnableExtensionChangeWarning"

# Desktop services settings
save_specific_setting "com.apple.desktopservices" "DSDontWriteNetworkStores"
save_specific_setting "com.apple.desktopservices" "DSDontWriteUSBStores"

echo "✓ Essential Finder settings synced to finder-settings.txt"