#!/bin/bash

# Load utils
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
if [ -f "$DOTFILES_DIR/lib/utils.sh" ]; then
    source "$DOTFILES_DIR/lib/utils.sh"
else
    echo "Error: utils.sh not found at $DOTFILES_DIR/lib/utils.sh"
    exit 1
fi

# Load defaults utilities
if [ -f "$DOTFILES_DIR/lib/defaults.sh" ]; then
    source "$DOTFILES_DIR/lib/defaults.sh"
else
    echo "Error: defaults.sh not found at $DOTFILES_DIR/lib/defaults.sh"
    exit 1
fi

check_macos

echo "Syncing Keyboard configurations..."

# 1. Sync modifier key mappings (Cmd/Ctrl swap etc.)
echo "Syncing modifier key mappings..."
save_modifier_key_mappings "$SCRIPT_DIR/modifier-keys.txt"

# 2. Sync macOS keyboard shortcuts using XML export approach
echo "Syncing macOS keyboard shortcuts..."

# IMPLEMENTATION NOTE:
# We use XML export for symbolic hotkeys instead of individual key management
# because it's the only reliable way to capture ALL system shortcuts including
# critical ones like Input Source switching (key 60). See lib/defaults.sh for
# detailed explanation of why this approach was chosen.

# Export ALL symbolic hotkeys using Apple's native XML format
save_all_symbolic_hotkeys_xml "$SCRIPT_DIR/keyboard-shortcuts.xml"

# Create simplified settings file for application shortcuts only
cat > "$SCRIPT_DIR/keyboard-settings.txt" << 'EOF'
# Application Keyboard Shortcuts Configuration  
# Generated by backup.sh
#
# NOTE: System keyboard shortcuts (Mission Control, Spotlight, Input Source, etc.)
# are managed separately in keyboard-shortcuts.xml using full XML export.
# This file only contains custom application shortcuts (NSUserKeyEquivalents).
#
# Format: app_domain|menu_item=shortcut_key
# Example: com.apple.finder|Show Package Contents=@\r
#
EOF

echo "# Current Application Shortcuts:" >> "$SCRIPT_DIR/keyboard-settings.txt"

# Save custom application shortcuts for common apps
save_app_shortcuts "NSGlobalDomain" "$SCRIPT_DIR/keyboard-settings.txt" "Global"
save_app_shortcuts "com.apple.finder" "$SCRIPT_DIR/keyboard-settings.txt" "Finder"
save_app_shortcuts "com.apple.TextEdit" "$SCRIPT_DIR/keyboard-settings.txt" "TextEdit"
save_app_shortcuts "com.googlecode.iterm2" "$SCRIPT_DIR/keyboard-settings.txt" "iTerm2"
save_app_shortcuts "com.microsoft.VSCode" "$SCRIPT_DIR/keyboard-settings.txt" "VS Code"

echo "✓ Keyboard shortcuts synced"

echo "✓ Keyboard configuration sync completed"