#!/bin/bash

# Load utils
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
if [ -f "$DOTFILES_DIR/lib/utils.sh" ]; then
    source "$DOTFILES_DIR/lib/utils.sh"
else
    echo "Error: utils.sh not found at $DOTFILES_DIR/lib/utils.sh"
    exit 1
fi

# Load defaults utilities  
if [ -f "$DOTFILES_DIR/lib/defaults.sh" ]; then
    source "$DOTFILES_DIR/lib/defaults.sh"
else
    echo "Error: defaults.sh not found at $DOTFILES_DIR/lib/defaults.sh"
    exit 1
fi

check_macos

echo "Syncing Keyboard configurations..."

# Create backup with timestamp
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="$SCRIPT_DIR/backups/$TIMESTAMP"
mkdir -p "$BACKUP_DIR"

# 1. Sync Karabiner-Elements settings
echo "Syncing Karabiner-Elements settings..."

KARABINER_CONFIG_DIR="$HOME/.config/karabiner"
if [ -f "$KARABINER_CONFIG_DIR/karabiner.json" ]; then
    # Backup current karabiner.json
    cp "$KARABINER_CONFIG_DIR/karabiner.json" "$BACKUP_DIR/karabiner.json.backup" 2>/dev/null || true
    
    # Copy current settings to module
    cp "$KARABINER_CONFIG_DIR/karabiner.json" "$SCRIPT_DIR/karabiner.json"
    echo "✓ Karabiner configuration synced"
else
    echo "Warning: Karabiner-Elements configuration not found at $KARABINER_CONFIG_DIR/karabiner.json"
fi

# Sync complex modifications
COMPLEX_MOD_DIR="$KARABINER_CONFIG_DIR/assets/complex_modifications"
if [ -d "$COMPLEX_MOD_DIR" ] && [ "$(ls -A "$COMPLEX_MOD_DIR" 2>/dev/null)" ]; then
    echo "Syncing complex modifications..."
    # Clean existing complex modifications in module (except .gitkeep)
    find "$SCRIPT_DIR/complex_modifications" -name "*.json" -delete 2>/dev/null || true
    
    # Copy current complex modifications (excluding system ones)
    for file in "$COMPLEX_MOD_DIR"/*.json; do
        if [ -f "$file" ]; then
            cp "$file" "$SCRIPT_DIR/complex_modifications/"
        fi
    done
    echo "✓ Complex modifications synced"
fi

# 2. Sync macOS keyboard shortcuts using defaults-based approach
echo "Syncing macOS keyboard shortcuts..."

# Create settings file header similar to finder-settings.txt
cat > "$SCRIPT_DIR/keyboard-settings.txt" << 'EOF'
# Keyboard Settings Configuration
# Generated by sync.sh

# Symbolic Hotkeys (System Keyboard Shortcuts)
# Common hotkey IDs:
# 32 = Mission Control
# 34 = Application Windows  
# 160 = Spotlight Search
# 65 = Show Spotlight
# 10,11,12,13 = Space shortcuts
# 15 = Desktop

# Global Application Shortcuts (NSUserKeyEquivalents)

# Custom Application Shortcuts
# Format: app_domain|menu_item=shortcut

EOF

echo "" >> "$SCRIPT_DIR/keyboard-settings.txt"
echo "# Current Settings:" >> "$SCRIPT_DIR/keyboard-settings.txt"

# Save important symbolic hotkeys (system keyboard shortcuts)
IMPORTANT_HOTKEYS="32 34 160 65 10 11 12 13 15"
for hotkey_id in $IMPORTANT_HOTKEYS; do
    save_symbolic_hotkey "$hotkey_id" "$SCRIPT_DIR/keyboard-settings.txt"
done

# Save custom application shortcuts for common apps
save_app_shortcuts "NSGlobalDomain" "$SCRIPT_DIR/keyboard-settings.txt" "Global"
save_app_shortcuts "com.apple.finder" "$SCRIPT_DIR/keyboard-settings.txt" "Finder"
save_app_shortcuts "com.apple.TextEdit" "$SCRIPT_DIR/keyboard-settings.txt" "TextEdit"
save_app_shortcuts "com.googlecode.iterm2" "$SCRIPT_DIR/keyboard-settings.txt" "iTerm2"
save_app_shortcuts "com.microsoft.VSCode" "$SCRIPT_DIR/keyboard-settings.txt" "VS Code"

# Create backup copy
cp "$SCRIPT_DIR/keyboard-settings.txt" "$BACKUP_DIR/keyboard-settings.txt.backup" 2>/dev/null || true

echo "✓ Keyboard shortcuts synced"

# 3. Create backup manifest
echo "Creating backup manifest..."
cat > "$BACKUP_DIR/manifest.txt" << EOF
Keyboard Module Backup - $TIMESTAMP
=====================================

Files backed up:
- karabiner.json.backup: Karabiner-Elements configuration
- keyboard-settings.txt.backup: macOS keyboard shortcuts and settings

Sync completed on: $(date)
EOF

echo "✓ Backup created at $BACKUP_DIR"
echo "✓ Keyboard configuration sync completed"
echo ""
echo "All keyboard settings have been synced to the module directory."
echo "Run init.sh to apply these settings on a new machine."